apiVersion: v1
kind: Secret
metadata:
  name: "{{.Chart.Name}}-secrets"
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  dbtype: {{ if .Values.postgresql.enabled }}{{ b64enc "pgsql" }}{{ else if .Values.mysql.enabled }}{{ b64enc "mysqli" }}{{ end }}
  dbuser: {{ default b64enc "moodle" b64enc .Values.database.user }}
  dbpassword: {{ default b64enc "moodle" b64enc .Values.database.password }}
