# Default values for moodle.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

moodle:
  image:
    repository: jbkc85/docker-moodle
    tag: v3.2r2017031601
    pullPolicy: IfNotPresent
  service:
    name: moodle
    type: ClusterIP
    externalPort: 80
    containerPort: 80
  replicas: 1
  resources:
    limits:
      cpu: 800m
      memory: 2056Mi
    requests:
      cpu: 500m
      memory: 512Mi
  metrics:
    image:
      repository: jecnua/apache-exporter
      tag: latest
      pullPolicy: IfNotPresent
    service:
      name: apache-exporter
      externalPort: 9117
      containerPort: 9117
    resources:
      limits:
        cpu: 75m
        memory: 15Mi
      requests:
        cpu: 50m
        memory: 10Mi

postgresql:
  enabled: true
  image: postgres
  imageTag: 9.6-alpine
  pullPolicy: IfNotPresent
  replicas: 1
  metrics:
    image:
      repository: wrouesnel/postgres_exporter
      tag: v0.1.2
      pullPolicy: IfNotPresent
      service:
        name: postgresql-exporter
        externalPort: 9187
        containerPort: 9187
      resources:
        limits:
          cpu: 75m
          memory: 15Mi
        requests:
          cpu: 50m
          memory: 10Mi

mysql:
  enabled: false
  image:
    repository: mysql
    tag: "5.7"
    pullPolicy: IfNotPresent
  service:
    name: mysql
  replicas: 1

memcached:
  enabled: false
  image: memcached
  imageTag: 1.4-alpine
  pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 100m
      memory: 72mi
    requests:
      cpu: 75m
      memory: 64mi
  metrics:
    image:
      repository: prom/memcached-exporter
      tag: latest
      pullPolicy: IfNotPresent
    service:
      name: memcached-exporter
      externalPort: 9106
      containerPort: 9106
    resources:
      limits:
        cpu: 75m
        memory: 15Mi
      requests:
        cpu: 50m
        memory: 10Mi
